### ISSUE TITLE
Want to join the textEncoding-Hub?

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#1]
Please respond here with your new GitHub account to ask to be added as a collaborator on this repo.

**Comment by zteyssier** [comment]
Hello @ebeshero, can I be added as a collaborator?  My username is @zteyssier, thanks!

**Comment by N00000DLE** [comment]
Hello! Please add me as a collaborator!

**Comment by am0eba-byte** [comment]
Hi! May I please be added as a collaborator? (this is Mia :)

**Comment by wdjacca** [comment]
Hello! Can I be added as a collaborator? This is Jackie!

**Comment by ebeshero** [comment]
@zteyssier @N00000DLE @am0eba-byte @wdjacca I've just sent you invitations to our textEncoding-Hub! Please check the email you used to set up your GitHub account and accept the invitation to join our repo.

**Comment by ebeshero** [comment]
@N00000DLE Which of my students might you be??? (The others have identified themselves. :-) )

**Comment by ebeshero** [comment]
@Kennaab I've just sent you an invitation to your email (the one you used to set up GitHub)--please check email to confirm!

**Comment by dxh405** [comment]
Hello! This is Daniel H. May I be added as a collaborator? My username is @dxh405

**Comment by amayadwillis** [comment]
Hello @ebeshero This is Amaya. May I be added as a collaborator? My username is @amayadwillis

**Comment by ebeshero** [comment]
@dxh405 and @amayadwillis : I've sent you both invitations! Check the email you used to set up GitHub to accept my invitation.

**Comment by Emily-Levi** [comment]
Can you add me as a collaborator?

**Comment by Scarlett-Lion** [comment]
hello this is Anthony V. may I be added as a collaborator? my username is @Scarlett-lion

**Comment by alexvanwoert** [comment]
Hi @ebeshero. Can I be added as a collaborator? My username is @alexvanwoert.

**Comment by ebeshero** [comment]
@Emily-Levi @Scarlett-Lion @alexvanwoert I've sent invitations to each of you: check the email that you used to set up GitHub to confirm and accept my invitation to join this repo.

**Comment by argynarg** [comment]
The account isn't new but it's still linked to my school account, can I be added as a collaborator?

**Comment by Beeplosion** [comment]
Hello @ebeshero this is Sebastian Ortiz can you add me as a collaborator, my username is @Beeplosion

**Comment by AliceR98** [comment]
Hello @ebeshero, This is Alice Rong. Can you please add me as a collaborator? My username is @AliceR98

**Comment by thompsonjosh24** [comment]
Hello @ebeshero, can you add me as a collaborator. My username is @thompsonjosh24

**Comment by Cameron-Bigi** [comment]
Hi @ebeshero, can you add me as a collaborator. Username is @Cameron-Bigi.

**Comment by trumerfe** [comment]
Hi @ebeshero, can you please add me as a collaborator? Username is @trumerfe

**Comment by sxa585** [comment]
Hey this is Sam my username is @sxa585. Can you please add me as a collaborator.

**Comment by AtomicOlsen** [comment]
Aidan Olsen, username is @AtomicOlsen. Please add me as a collaborator.

**Comment by ebeshero** [comment]
@argynarg @Beeplosion @AliceR98 @thompsonjosh24 @Cameron-Bigi @trumerfe @amw6765 @sxa585 @AtomicOlsen Please check the email you used to create your GitHub account! I've sent you invitations to join that you will need to accept. :-)

**Comment by Joelpie** [comment]
Howdy @ebeshero, this is Joel Watson, my username is @Joelpie and I'd like to be added here.

**Comment by bwm5473** [comment]
Hi, it's Brett Meyer. May I please be a collaborator?

**Comment by BarbieCessar** [comment]
Hi, it's Barbie Cessar!

**Comment by ebeshero** [comment]
@Joelpie @bwm5473 @BarbieCessar I've belatedly sent you three invitations to this GitHub repo! Please check your email that you used to set up GitHub and make sure you accept my invitation.
