### ISSUE TITLE
Red box on goodMorning 

### ISSUE THREAD

**Issue by N00000DLE** [newtfire/textEncoding-Hub#14]
I followed the lecture again and my schema has a green box, but I am having an issue when putting them together. It is giving me red on my <xml>. I have tried a bunch of stuff but nothing changed it. Images below for reference (That is only part of my code).

![image](https://user-images.githubusercontent.com/60856407/93255054-53edb180-f767-11ea-95db-4c7d2c243b8d.png)

![image](https://user-images.githubusercontent.com/60856407/93255095-6667eb00-f767-11ea-9f47-c26300adcd14.png)

**Comment by Emily-Levi** [comment]
I'm also having the same issue.

**Comment by ebeshero** [comment]
@N00000DLE The schema you wrote doesn't actually reflect the elements in the goodMorning.xml document. That is why it's giving you an error from the root element. 

Notice that the name of the root element is not `<goodMorning>`. It is `<xml>`. So you need your schema to give the actual name of the element. Start by revising your schema to reflect what's actually in the document. So, start with this:

```
start = root
root = element xml {     }
```

Now, what is inside the xml root element? We have to fill in the part inside those curly braces. The xml root element contains the outer elements in the document. What are they? Well, `<source>` and `<text>`, right? Inside `<xml>` there is a `<source>` element and a `<text>` element. So prepare your schema to reflect that: 

```
start = root
root = element xml {source, text}

```
There is no id attribute on the root element, so I don't really understand why you're writing that line in that way? I don't understand why you have schema lines written that don't actually reflect the elements we see in the document!  What you want to do is work your way step by step from the root element through the XML tree structure of your document, and define what's immediately inside each element as you go.  So, next, how do you define the `<source>` element? 

```
source = element source {         }
```
Well, let's take a look at goodMorning.xml and see what's inside `<source>`: I see:
```
 <source>
        <title level="book">Montage of a Dream Deferred</title>
        <altTitle>Harlem</altTitle>
        <author>Langston Hughes</author>
        <pubPlace where="NYC">New York</pubPlace>
        <publisher>Henry Holt and Company</publisher>
        <date when="1951"/>
        <note>Book length poem</note>
    </source>
```
So, source contains the elements `<title>`, `<altTitle>`, `<author>`, `<pubPlace>`, `<publisher>`, `<date>`, and `<note>`. Don't worry about their attributes or contents, yet--you just need to indicate that `<source>` contains *that specific series of elements* like so: 

```
source = element source {title, altTitle, author, pubPlace, publisher, date, note }
```

From there, Relax NG will prompt you to define each of those elements. You'll need to indicate their contents, including attributes and whatever's inside, elements or text, or some mix of both. So let's keep on going with writing rules step by step for what's actually in the goodMorning.xml document.

Then when you go to associate your schema, you'll see how well your schema reflects the XML structure of the document. Does that help?

**Comment by ebeshero** [comment]
@N00000DLE @Emily-Levi Let's keep going with this so you have a better view of how the schema writing is supposed to work:

```
start = root
root = element xml {source, text}
source = element source {title, altTitle, author, pubPlace, publisher, date, note }
title = element title { level, text   }
level = attribute level {"book"}
altTitle = element altTitle {text}
author = element author {  }
# keep on going until you define every element inside <source>
# Then go up and define what elements are inside <text>

```
The `<text>` element will be tricky to define because the element has the same name as a reserve word in Relax NG. We solve that problem following the advice posted here: https://github.com/newtfire/textEncoding-Hub/issues/13
