### ISSUE TITLE
Syntax Error on Relax NG Exercise 2

### ISSUE THREAD

**Issue by natalyamyers** [newtfire/textEncoding-Hub#15]
I'm getting a general syntax error on my xml document after I associate my schema. I feel like it's a pretty obvious problem, but I've just been staring at it for a while and I think I need a pair of fresh eyes to help point out the issue.
<img width="921" alt="SyntaxErrorSchema" src="https://user-images.githubusercontent.com/70730578/93629947-2303bb80-f9b7-11ea-92be-cfad04448153.PNG">

**Comment by ebeshero** [comment]
@natalyamyers Sorry I missed seeing your post! I can't see the source of the error here: the schema looks right to me, although in your rule for the `<sent>` element, I would move the `n` attribute outside of mixed{}. That won't cause a syntax error, though...

If you haven't solved this already, what's the text of the error message you're seeing?

**Comment by natalyamyers** [comment]
@ebeshero no text error, just giving me the syntax error with no information on it

**Comment by ebeshero** [comment]
@natalyamyers I can't tell what's wrong from the screen capture. I'd need to see the files. But try saving both the schema and the XML file, and then, with your cursor in the XML file, click the red checkmark button in oXygen to refresh the schema validation. Does that take care of it?
