### ISSUE TITLE
TEI Exercise 1: Suggestions for encoding Anna Julia Cooper's survey responses in TEI

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#19]
Post your responses to [TEI Exercise 1](https://newtfire.org/courses/tutorials/TEI-AJC-Exercise1.html) here. What ideas do you have about: 
* what kinds of data need to be marked up in the survey
* how we should approach this using the TEI?

**Comment by ebeshero** [comment]
Here is an element I think might work to represent Anna Cooper's handwriting on the form:
[the TEI `<add>` element](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-add.html)

**Comment by AliceR98** [comment]
I feel like, in terms of the document structure itself, the more basic things that should be marked down are the main sections of the survey, such as "Undergraduate History", "After Graduation Career", etc. Other things would include the numbered survey questions, the tables used, a distinction between handwritten and printed text, the checkmarks used throughout the survey, the document title and number, and where the document is stored. 

For the information outside of the contents, such as the document number, institution, and the repository in which the document is stored, [TEI's `<msDesc>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-msDesc.html)could be used. Within msDesc would include [the `<msIdentifier>` tag](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-msIdentifier.html) and within that would include the name Howard University, which could be wrapped between the `<settlement>` tag, while "Moorland-Spingarn Research Center" can be wrapped with the `<repository>` tag. It could also include a [`<idno>` tag](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-idno.html) as well. Meanwhile, an alternate id number such as the red number at the top right corner of the document's first page would also be tagged with `<idno>`, but according to TEI, it would be categorized under `<altIdentifier>`. So it would look something like this:

```
<msDesc>
     <msIdentifier>
          <settlement> Howard University </settlement>
          <repository> Moorland-Spingarn Research Center</repository>
          <idno>[id number goes here]</idno>
          <altIdentifier>
               <idno>3533</idno>
          </altIdentifier>
     </msIdentifier>
</msDesc>
```

The title of the document would go in  [`<titlePage>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-titlePage.html) which would then include [`<docTitle>`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-docTitle.html) and then have "Negro College Graduates" and "Individual Occupational History" being wrapped in separate [`<titlePart>` tags](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-titlePart.html). According to TEI, all of that would also be wrapped in a `<front>` tag like this:

```
<front>
     <titlePage>
          <docTitle>
               <titlePart type ="main"> Negro College Graduates </titlePart>
               <titlePart type = "sub> Individual Occupational History </titlePart>
          </docTitle>
     </titlePage>
</front>
```

For the main sections, I believe one thing that might work is [a TEI `<div>` element](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-div.html). Specifically, you could wrap the sections in `<div1 type ="section" n = "I">`, with the specific section names being wrapped with a `<head>` tag. meanwhile the numbered questions within each section could be wrapped in `<div2 type="question' n="1">` with the actual typed question being wrapped in `<add type="#[insert id here]">` and the handwritten answer being wrapped in `<add hand="#AJC">`. This of course uses the TEI `<add>` element to differentiate between handwritten and printed text, though such the ids must be referenced by a [TEI `<typeNote>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-typeNote.html) or [a `<handNote>`](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-handNote.html) somewhere else in the document. 

There are also checkmarks used throughout the document, though I cannot find an exact TEI guideline that might indicate what to do about that. The only suggestion I have is to do something like: `<add hand="#AJC"><checkmark /> </add>`. In terms of the tables, I believe it's best to follow [the TEI table guidelines](https://tei-c.org/release/doc/tei-p5-doc/en/html/FT.html) when marking them up. 

Other smaller things include marking up names of people and places with a `<name>` tag.

**Comment by AtomicOlsen** [comment]
I'd like to break this into two pieces based off the initial comment you made:
<h3>what kinds of data need to be marked up in the survey?</h3>
First there needs to be a complete rendition of the survey, anything not handwritten needs marked down clearly, as to not lose arguably the most important part of the document the questions and framing of them, Mrs. Cooper has quite a bit of overlap in this form, lots of her words drag into margins and upside-down at some points, this is really important to note as it's what gives her writing character along with noting that she had a lot to say (to say the least)
As far as what kinds of data in particular?

First off we need to see the questions distinctly marked. Question one, the question, Mrs. Cooper's response, and anything interesting about the handwriting in that question, I feel this is the cleanest way to get the data organized in a way that enables us to pull more from it (through writing XML) I think of what we have right now is pre-xml, where we're doing a surface-clean of the document before really dragging a comb through it.

<h3>how we should approach this using the TEI?</h3>

We need metadata about the document, the metadata should be wrapped completely. 4.6 of the TEI encompasses this within their Title pages section, and the tags listed throughout that section echo the sentiment.  

After Metadata is out of the way, we can begin to separate the text into two main portions, questions, and answers (which can be dictated via author tags with who attributes) Within Mrs. Cooper's writing, what we see very often are run-offs into margins which can be annotated with the [`<add>`] (https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-add.html) tag. 
`<address>` can be used to amend the address that Mrs. Cooper provides as well. After using the TEI to surface-clean, we can then go deeper and flesh the XML out with anything from names and places to word choice, which as Mrs. Cooper was a teacher, her word choice could be something interesting to look at.

**Comment by ebeshero** [comment]
Thanks for getting this started, @AliceR98 and @AtomicOlsen ! These are very good observations and suggestions: You’re noticing the kinds of information we should try to mark, and pointing to good passages you found in the Guidelines to help. I am going to try introducing a TEI document tomorrow that responds to the class’s suggestions in this thread, so I’m eager to see how this develops!

**Comment by BarbieCessar** [comment]
what kinds of data need to be marked up in the survey:
All data has to be transcribed into text and then it should be marked up in a way that makes sense with the structure of the survey.  I would first start by marking up the title and sub title. Then I would take time to organize each question, identifying the question, the number, and the answer. As I was studying the Manuscript description page I found specific elements for the title page and the element <handNote> for Julia Cooper's handwritten answers. 

Here is an example of how I would approach the survey using the TEI:

<titlePage><settlement>Howard University </settlement> 
<repository>Digital Howard  Howard University</repository>
<msIdentifier>tBiographical Data  Personal Papers</msIdentifier>
<docDate>October 2017</docDate>
<docTitle>Negro College Graduates Individual Occupational History</docTitle>
<notes>Follow this and additional works at: http://dh.howard.edu/ajc_bio</notes>
<docImprint> Recommended Citation"Negro College Graduates Individual Occupational History" (2017). Biographical Data. 2. http://dh.howard.edu/ajc_bio/2</docImprint>

MsDesc><watermark> Moorland-Springarn Research Center </watermark> 
<title> Negro College Graduates </title> <titlePage> 
<head type = "sub"> Individual Occupational History</head>
<question  type = "name" n = "1"><handNote>Anna Julia Cooper<handNote></question> 
<question type = "Present address" n ="2"><handNote> 201 T N.W.</question>
<question type = "maiden name" n = "3" ><handNote> Anna Julia Haywood</handnote> </question>

And I would continue this pattern with all of the question on the survey.

**Comment by zteyssier** [comment]
1.  The data needs to be transcribed first.  The handwriting provided is mostly legible, although she writes upside-down and scrunches her words at times.  We could use each of the major outlines (ex. I. Social Information) as a basis to mark up the data.  We can expand by focusing on her various occupations, her performance during her undergraduate career, her graduate enlightenment, and her special comments as well.  Providing continuity and a true representation of the question and answer format on XML may present a challenge.  

2. Some of the text is truncated from the scanner.  This could potentially impact the markup.  I wonder if the TEI has any rules on how to deal with this issue.  Is it alright to assume what the letters/words are or should be?  

Providing metadata about the document such as the context surrounding the document will help to categorize this document with similar documents in the future.  Paying attention to detail will help to markup this document ethically, and accurately.  Taking note of the Form number:  3533 will help with organization.  Having each question associated with each of Mrs. Cooper's answers will help enforce integrity.  

![TEI-Schema-DIGIT-110](https://user-images.githubusercontent.com/70618741/94627103-a2806d00-028a-11eb-86f3-8d430748edb3.PNG)

This portion can help when developing the RNG schema.  Elements such as **<add>** can mark where new information presents clarification.  

![Setting-DIGIT-110](https://user-images.githubusercontent.com/70618741/94627484-acef3680-028b-11eb-87ec-250c845e954f.PNG)

I think using conventional elements such as <name>, <date>, <time>, <locale>, and <activity> can eliminate confusion with a variation in the markup.  Appropiate attributes associated with each can provide additional information about a specific passage.

**Comment by am0eba-byte** [comment]
The survey consists of section labels, typewritten script, handwritten responses, tables with labels and columns, multiple-choice questions that are ticked by Anna Cooper, and the last page contains handwritten continuations of responses that reference previous survey questions in the document. These are just a few meta-descriptions about the document that we should probably mark up.

I think, to approach this document in TEI, we should probably begin by wrapping typewritten script with the element ```<typeDesc>```, and handwritten responses from Cooper with ```<handDesc>```. Within these two elements, the element ```<p>``` should be used to indicate paragraphs or sections of handwritten/typed text. [Here's that section in the TEI handbook](https://tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msph2) Example:
```
<typeDesc>
    <p> 13. Do you own a home?</p>
</typeDesc>
<handDesc>
     <p> Yes </p>
</handDesc>
```

 [To document the typed layouts of tables](https://tei-c.org/release/doc/tei-p5-doc/en/html/MS.html#msphla) (like the dead children section), we should use the element ```<layout>``` followed by attributes ```<layout columns="5">```, with the attribute value indicating how many columns are in the table. You could also use the element ```<layout>``` to document ticked lines written on the survey by Cooper. 

Alas, I have absolutely no clue what attribute/attribute values to use to document the ticked answers; I couldn't find the specifications for it. But I'm pretty sure we do need to use the layout element.

[To document multiple-choice questions in the survey,](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#COLI) I'm pretty sure we can use the element ```<list rend="inline numbered">``` to wrap the survey question itself, and wrap each individual lettered choice with ```<item n="a | b | c | d ...">``` Again, I still have no idea how to indicate the answers that she ticked off or selected, so if anyone has any ideas on that and would like to comment that'd be absolutely nifty and grand.

**Comment by Emily-Levi** [comment]
In the survey I think  the main points that should be marked up are personal information and undergraduate history. From there information should be organized and marked up within those categories. Also Julie Coopers handwriting specifically her marginal notes should be marked up. 


Using TEI we could include the msIdentifier tag to identify the survey as an overall document. The TEI note component element of misItem can be used to mark Cooper's side comments in the survey. The TEI additions element can also be used to indicate side comments in the margins as well.

**Comment by wdjacca** [comment]
I think one important part of the survey is the background history of Anna Julia Cooper, much like how we did before doing this exercise. To do so, I think the <history> (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-history.html) or the <additional> (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-additional.html) tags would work well. 

The tag <msPart> (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-msPart.html) can also be used to identify the parts that are written by Anna Julia Cooper, especially the longer answers that she has. 

After reading the posts above by other classmates, I think one of the main problem is the marking of the check marks Cooper makes in her survey answers. I think the <pc> (https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-pc.html) element with an attribute of <type ="check"> may work well.

**Comment by Beeplosion** [comment]
As I went along with the work I noticed that the main information to markup includes the undergraduate history due to its large amount of information and some of her personal history because of how specific to her it is.

In regards to TEI, I am still a bit confused, but to my best guess, I would say it is best to use things such as <msIndetifier> and <msContent> to describe the actual documents themself and to describe what is actually there to go through. I noticed there is heavy usage of watermarks which could impact the reader's experience so it is important to acknowledge so.

**Comment by alexvanwoert** [comment]
The survey was completed with hand written and multiple choice answers. They can be organized into sections based on the survey such as "Undergraduate History" and "Social Information" using metadata tags like [<'teiHeader'>](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-teiHeader.html). The tables, multiple choices, answers in the margins, and additional markings would be labeled appropriately using TEI. For the tables and multiple choice you could use the [<'list'>](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-list.html) tag and the [<'note'>](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-note.html) tag for the additional markings in the margins. Any person, place, or object written as an answer can be marked by the [ <'rs'> ](https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-rs.html) tag with a corresponding attribute value, such as type="person". 

The context articles give valuable insight to marking up the survey for future use with related documents. Most of the content was legible including a majority of the notes squeezed into the margins of the long response questions. All the information from this survey could be put into a large, organized timeline of Dr. Cooper's life using universal TEI markup on other documents.

**Comment by Kennaab** [comment]
When looking through the website, I noticed that there is a lot of numbered lists that they could be used with XML markup. Such as when she is listing her children living. The [`person`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-listPerson.html) element.

![image](https://user-images.githubusercontent.com/70358707/94639154-9e177c80-02a9-11eb-8dd8-c2311423e51f.png)

There is also a section in the document where XML could be used to show how she is related tp the people she wrote down (her brothers). When she is listing her [`name`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-name.html) there could be an XML format. The [`address`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONAAD) , her [`surname`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-surname.html), her [`salary`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONANU).

 When she using the 'space reserved for special comment' you could use [`note`](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-note.html). Pretty much everything on this document can be used with some type of markup. There's plenty of options when diving deep into the TEI. 

I truly wasn't expecting there to be so many options with everything but there definitely is. It goes to show how broad XML markup is and how it can be used for almost anything that is in a document format.

**Comment by Cameron-Bigi** [comment]
Some of the main points that I believe should be put into mark up is her personal information and background history. Specifically her background history of her Undergraduate History, possibly using the tag of <history>. On how to approach this with TEI, I think that this document needs more metadata. Adding more metadata will help to add more context to the document and help it make a bit more sense.

**Comment by argynarg** [comment]
When looking over this document there are a few things I immediately took notice of, the first of which is the charts that will need to be sorted. Each page also has handwritten notes on the side that will need their own place in the transcript. The first page would also need to be differentiated from the rest as it is a later addition to the document. 
To begin I would use <typeDesc> and <scriptDesc> to differentiate between typewritten and handwritten portions. I would use <docDate>, <docTitle>, and <author> for the title page amongst other tags. The last page seems like a good section for use of <note> for the comments on the side that are separate from the rest of the text.

**Comment by N00000DLE** [comment]
When looking over her survey, they have handwriting on printed pages. I think you would first need to transcribe all of her writing & survey question into legible code. Using markup techniques this is easily possible. I would say comparable to some projects we have worked on in the past where multiple people work together to work on a page. Setting up a format for marking up all the questions in the survey the same is important, so we can track relevant information in the survey. There should also be a marked difference in printed or handwritten text. For information other than the survey a simple markup would be key, just to track things such as titles or descriptions on the page.

When looking into TEI one thing that comes up early in the document is tables. TEI has a section on how to mark them: 
![image](https://user-images.githubusercontent.com/60856407/94681108-e017e100-02f0-11eb-8f19-7c241d0050e3.png)

**Comment by amayadwillis** [comment]
I think it is important to use markup to identify different sections of the document, the questions and answers, and any interesting/different handwritten things (such as crossed out words, inserted words, and writing in the margins). I noticed that there are watermarks completely covering the pages, so perhaps it would be a good idea to include those in the markup somehow. 
As for the TEI I guess I've not had enough time to really grasp everything, it seems like a lot of information to take in, so I don't really have any good ideas for the approach that should be used.

**Comment by Scarlett-Lion** [comment]
**What to mark up:**
•	Names
•	Addresses
•	Maiden name (option)
•	Length of residency
•	Age
•	Gender
•	Date of birth
•	Place of birth
•	Date of marriage
•	Age at marriage
•	Date
•	Page
•	Number of questions
•	Group of questions
•	Question section
•	Comment section
•	Info section
•	Title
•	Introduction page

As for how we approach using the TEI, it shouldn't be too different for what we been doing in class. make sure you mark everything up, divide different sections up, and fork on one section at a time. will making sure is you use a mark up to define a type of thing then use the same mark up for similar things.

**Comment by amw6765** [comment]
The first rules that you could use from the TEI is section 3.5 Names, Numbers,  Dates, Abbreviations, and addresses. The first section from the Cooper form is all general demographics about her. 
![Screen Shot 2020-09-30 at 11 19 13 AM](https://user-images.githubusercontent.com/70722523/94705529-29772900-030f-11eb-8d93-98a9ab8ed283.png)

The next rule from the TEI that applies to Anna's college graduate form is chapter 11 section 3.1.1 Corre Elements for Transcriptional Work. Throughout this form she makes changes and corrections to the prompt questions. She changes them and makes them apply to her more than the original prompt had. All of the corrections and abbreviations can be easily documented using these rules from this chapter. 
![Screen Shot 2020-09-30 at 11 24 05 AM](https://user-images.githubusercontent.com/70722523/94706316-09943500-0310-11eb-9bf3-124d8b4a67b1.png)

The third chapter and rule that I found to relate to this form is from chapter 10 section 0.2. In this section they discuss how to properly treat the different elements of manuscript and content that is within a document. Because most of this paper contains Cooper's handwriting, this TEI element rule would be able to be used in a transcription of this document.
![Screen Shot 2020-09-30 at 11 24 05 AM](https://user-images.githubusercontent.com/70722523/94706834-b2429480-0310-11eb-8b7b-353f25a827f7.png)

There is a lot of different parts of this form that can be contained within different types of markup. From what I was able to understand these are the different rules that can be used for this. However, understanding the TEI is seeming to be more difficult than I had imagined.

**Comment by sxa585** [comment]
The kind of things about this survey that need to be marked up are the obvious ones like the history of her life the dates and times things along that nature, but I also think they stay true to the person that wrote them. If you look at the Special comment section you can see a lot of her views on things, I think this is almost more important so you have a visualization of who she was as a person and not just the respondent of a survey.

Using TEI, the amount of different notes to take in kind of made it seem like I am going to make mistakes, as everyone does. But as someone who believes in keeping historical accuracy, I don't wanna mess to much up. The description TEI provides for every element I think will help with that. I think we will be using it to mark up the code in a way so that you understand how it was written and the context surrounding that why, with all the elements that are available within the giant schema that is the TEI, as well as guidance I believe this is very easily achievable.

**Comment by natalyamyers** [comment]
The types of information that should be marked up include the big sections, like others have mentioned, that include her life's history. I feel like marking up these sections that physically contain a lot of content could make them easier to digest and understand.
As for the TEI encoding, so far I don't think I am understanding a lot of it, but the TEI guidelines are helping a bit with that. Reading other's responses to this hub is also giving me a bit more insight into how I can use tags and what they should be used for.
