### ISSUE TITLE
How to markup unclear text?

### ISSUE THREAD

**Issue by AliceR98** [newtfire/textEncoding-Hub#21]
There are parts within the survey where I can't make out what the cursive is saying. Is there a way to mark that up in the code?

**Comment by ebeshero** [comment]
@AliceR98 Yes indeed there is! Try looking at these elements in the TEI:

* **[unclear](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-unclear.html)**
* **[gap](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-gap.html)** (for when something is literally missing and you can't see it at all, like if it's cut off on the page or by the photo not catching everything.
