### ISSUE TITLE
How to search for specific tags within TEI? Struggling with starting point for encoding.

### ISSUE THREAD

**Issue by AtomicOlsen** [newtfire/textEncoding-Hub#22]
What is the best angle of approach to take to find the correct tags I need to begin encoding my information. 
![image](https://user-images.githubusercontent.com/55807185/95099212-9f0f3a80-06fd-11eb-894d-9b529d3127e5.png) for example, I want to take each question, and separate them from the answer. First I tried to wrap them in a division and it flagged wrong (although the error text had div included within the "Tags must be one of:__,__,") So I tried to search for which to use, Author doesn't seem correct, and now I'm stuck sifting through endless pages of tags with no real goal in mind, it's severely hurting my workflow. I have no problem with XML, I can make my own schema, I can make some clean XML mark, but when it comes to trying to follow someone else's rules I'm falling flat.

**Comment by ebeshero** [comment]
@AtomicOlsen TEI is long and slow work, and sometimes you stumble into a pretty good combination. 
You can definitely work with `<div>` elements: I don't know what error you were seeing, but if you're stuck like that, it helps to document the error and show that specific code you tried. (Paste the into the message, so we can try it ourselves and try to fix it!) You can try making a code block here in the issue, too. The screen capture here doesn't show the error. 

Here is one that you might want to try out, the `<ab>` element:
https://tei-c.org/release/doc/tei-p5-doc/en/html/ref-ab.html
Notice that this can include an `<add>` element that could be helpful.
