### ISSUE TITLE
Writing Relax-NG schema and coding our Semester project to fit within rules of XHTML5

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/textEncoding-Hub#26]
I'm sort of stuck on how we should encode our project to be visible in our project websites in HTML. I'm realizing that it'll be really difficult to try to define and code all the different aspects of our document to fit within the bounds of both a Relax-NG schema and HTML - are we supposed to code our project documents in XML first, to be associated with the schema we write for it, and then somehow convert that into HTML? For example, I am trying to code my xhtml 5 document for the project text using the TEI guidelines as a sort of guide, but XHTML 5 doesn't want me to use elements like `<pg/>`, `<sp>`, `<author>`, and `<castList>` in my `<body>` element - which are  sort of crucial elements to capture the parts of my document in code. Are we supposed to code the document in XML first? How is this going to turn into HTML and be visible on our websites while also keeping our defining elements true to our goals for coding the project?

**Comment by ebeshero** [comment]
@am0eba-byte No worries! You're about to learn how to write transformation code called XSLT to transform your XML to other forms of markup language, including HTML! So you'll be modeling how to take your `<pb/>`, `<sp>` and other elements and output them in HTML's more limited tagset for display on the web. So, for right now, worry not about how this turns into HTML, but concentrate on the *semantic* (meaningful) modeling in XML!

**Comment by am0eba-byte** [comment]
Oh great! So we code the document in XML, and we are still pushing that xml document and its associated schema up to our project repo? And it's okay if they aren't linked to our project websites?

**Comment by ebeshero** [comment]
@am0eba-byte Yes! For tomorrow you are just pushing some XML and Relax NG up to your GitHub repo.
