### ISSUE TITLE
Adding Hub Collaborators

### ISSUE THREAD

**Issue by austinmurry** [newtfire/textEncoding-Hub#37]
My username is @austinmurry. Please @ebeshero add me as a collaborator to this Hub.

**Comment by arrowarchive** [comment]
My name is Rachel, but I go by @arrowarchive. If you would, @ebeshero, please add me as a collaborator to this hub.

**Comment by erinmooney** [comment]
Hey, this is Erin! I am also @erinmooney. Please add me as a collaborator to this hub @ebeshero.

**Comment by Yuying-Jin** [comment]
Hi @ebeshero! Please add me as a collaborator to this hub. My username is @Yuying-Jin.

**Comment by ericsandbloom** [comment]
I'm Eric and I go by Eric, crazy. I do art and stuff.

**Comment by jbg5721** [comment]
Hello, may I please be added as a collaborator @ebeshero ? My username is @jbg5721

**Comment by Tiny-Pickles** [comment]
Hello I hope life is good! I'm Grace but I am also @Tiny-Pickles. Please add me as a collaborator to this hub @ebeshero. Thank you!

**Comment by Janman813** [comment]
Hello, this Janet also known as @janman813 please add me as a collaborator @ebeshero. Thank you!

**Comment by kmh6907** [comment]
Hi I'm Kat! Please add me as a collaborator @kmh6907 , @ebeshero Thanks a bunch!

**Comment by NickyV1234** [comment]
HI im Nicky I would like to be a collaborator @ebeshero my account is @NickyV1234

**Comment by bealse18** [comment]
Hi I'm Sydney. My username is @bealse18 , Please add me as a collaborator @ebeshero

**Comment by luh429** [comment]
My username is @luh429 and my real name is Logan Hering. Please @ebeshero add me as a collaborator to this Hub.

**Comment by A-Little-Coconut** [comment]
This is Graesyn. My username is @A_Little_Coconut, please add me as a collaborator.

**Comment by A-Little-Coconut** [comment]
This is Graesyn. My username is @A-Little-Coconut , please add me as a collaborator.

**Comment by ebeshero** [comment]
If you have requested me to add you before 12:03am on Friday Sept. 3, I have sent you an invitation to join this repo. Please check the email you used to set up your GitHub account to find and accept my invitation.

**Comment by hjl5363** [comment]
My name is @hjl5363. @ebeshero - please add me as a collaborator to this DHClass-Hub.

**Comment by ZakMurphy191** [comment]
My username is @ZakMurphy191 Please @ebeshero add me as a collaborator to this Hub.

**Comment by aidanvray** [comment]
I'm @aidanvray. Can @ebeshero please add me as a collaborator.

**Comment by lbanic** [comment]
I am @lbanic, @ebeshero please add me as a collaborator.

**Comment by nickwright11** [comment]
Hi, my username is @nickwright11, please add me as a collaborator @ebeshero

**Comment by acc5763** [comment]
Hi, my name is @acc5763, please add me as a collaborator.

**Comment by ebeshero** [comment]
Okay! I have now added everyone who requested to join this repo as of 7pm on Friday Sept. 3. **Please check the email you used to set up your GitHub account to find and accept my invitation.**
