### ISSUE TITLE
Welcome new DIGIT 110 collaborators!

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#50]
When you have created your GitHub account, please post in response to this to request me to add you to our textEncoding-Hub repo! Please identify yourself and try writing something in GitHub markdown, too. :-)

**Comment by kzp308** [comment]
Hi this is Kyara, requesting to be added.

**Comment by tec5271** [comment]
This is Tyler. Looking to be added to the textEncoding-Hub repo.

**Comment by JiayuanWen** [comment]
This is Jiayuan Wen, looking to be added.

**Comment by fkb5105** [comment]
Hi it's Felipe requesting to be added

**Comment by MyeishaF** [comment]
Hi this is Myeisha, requesting to be added!

**Comment by MinWu859** [comment]
Hi it's Min Wu requesting to be added

**Comment by jms9354** [comment]
Hello

**Comment by jms9354** [comment]
Hello, this is Jermaine requesting to be added

**Comment by WillStill** [comment]
Hi it's Will requesting to be added!

**Comment by gzc5211** [comment]
Hello, this is David, requesting to be added.

**Comment by Stach13** [comment]
Hello, this is Noah, requesting to be added.

**Comment by julianjmg** [comment]
Hi! this is Julian. add me please

**Comment by ZSchleger** [comment]
This is Zach, Requesting to be added

**Comment by Tonya-Velcko** [comment]
This is Tonya requesting to be added.

**Comment by JaxAbele** [comment]
This is Jax Abele requesting to be added!

**Comment by ebeshero** [comment]
If I've entered an emoji on your request, I've just sent you an invitation to collaborate on this textEncoding-Hub for our class. Please check your email to find my invitation and accept it, and you'll then have access to our class repo. We'll be testing this access soon!

**Comment by jdh6067** [comment]
Jake here please add me

**Comment by epp5198** [comment]
This is Egan requesting to be added

**Comment by spookybeetle** [comment]
This is Milo requesting to be added.

**Comment by ztd5049** [comment]
Hey Zack here, add me to the repo

**Comment by SteveXC1** [comment]
This is Stephen requesting to be added.

**Comment by ebeshero** [comment]
Sorry for not getting back to adding you until 5pm today, but so far, everyone ahead of this message, with a thumbs-up emoji on your post, has been sent an invitation to join this repo. 
** Each of you, please check your email to find my invitation and accept it, and you'll then have access to our class repo.**

**Comment by Mortalgamer45** [comment]
This is Shamaun requesting to be added.

**Comment by ebeshero** [comment]
@ShamaunStrickland Okay! I've just sent you an invitation to join the repo.
**Please check your email to find my invitation and accept it, and you'll then have access to our class repo.**

**Comment by JiminyKricket0323** [comment]
This is @JiminyKricket0323, @ebeshero requesting to be added. (Git Exercise 1)
