### ISSUE TITLE
Adding Hub Collaborators 

### ISSUE THREAD

**Issue by Stach13** [newtfire/textEncoding-Hub#54]
My username is @Stach, @ebeshero please add me as a collaborator to this DHClass-Hub.

**Comment by ebeshero** [comment]
@Stach13 Careful! Your username is really `Stach13`! I've already sent you an invitation to join the repo: check the e-mail you used  when you configured your GitHub account for a message from me inviting you to this repo, and go and accept my invitation! 👍

**Comment by ebeshero** [comment]
@Stach13 I'm checking to make sure students are members of this textEncoding-Hub and I'm thinking you might still not have accepted the invitation? I'm going to try uninviting and reinviting you: When you see an email inviting you to join the textEncoding-Hub, please accept the invitation, and you'll have push access to the repo then.

**Comment by ebeshero** [comment]
@Stach13 Scratch that. I'm going to leave the existing invitation in place. I can't actually tell easily from here whether you have push access to the repo or not... Just please look in your PSU and/or other email and see if you have an invitation to join the textEncoding-Hub. Accept it.
