### ISSUE TITLE
Did not receive collaborator invite

### ISSUE THREAD

**Issue by Tonya-Velcko** [newtfire/textEncoding-Hub#56]
Hey, @ebeshero. I never received an email inviting me to join the repo. I checked my settings and I think it might have been because I accidently set my email to private and GitHub sent the invite somewhere else. It should be fixed now, so could you send me another invite? My username is @Tonya-Velcko.

**Comment by ebeshero** [comment]
@Tonya-Velcko Evidently you are already a member of the repo, so I think it *did* go through after all? 
(You've successfully pushed to the textEncoding-Hub, and I see you here with the role of "Maintainer", so you're already here!

<img width="1187" alt="Screen Shot 2022-09-06 at 20 47 22" src="https://user-images.githubusercontent.com/4014518/188764688-1c147855-3d85-4672-97eb-8517027f218d.png">

**Comment by Tonya-Velcko** [comment]
Yeah, I saw "member" and was confused because I never accepted the invite because I didn't receive it. Thanks for checking!
