### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by tec5271** [newtfire/textEncoding-Hub#59]
Looking to be added to the textEncoding-Hub

**Comment by ebeshero** [comment]
@tec5271 Look for an invitation in your email (might have been days ago) from the textEncoding-Hub to join the repo, and accept the invitation.

**Comment by ebeshero** [comment]
@tec5271 Do you need me to uninvite and reinvite you (can't find the invitation?)

**Comment by ebeshero** [comment]
@tec5271 And that seems no easy matter. I want to make sure you definitely cannot find the invitation to join the repo in your email before I do something drastic like that.
