### ISSUE TITLE
Messing with Markdown

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#6]
This is an issue to help introduce you to GitHub's Markdown. 

# Heading 1
### heading 3

- list item

- list item
   - list in list

Sharing code in code blocks:
`<tags>`  are going to disappear
Code block:

```xml
<xml>
     <tag type="markup">Markup is awesome!</tag>
</xml>

```

**Comment by AtomicOlsen** [comment]
#### This
## Is
# Markdown

>This is a quote

*Italics*
**Bold!**
_**BOLD ITALICS**_

**Comment by dxh405** [comment]
**BOLD**
*Italics*

As Danny once said:
> I Hope this works
> If not that is embarrassing

**Comment by amw6765** [comment]
# I Can Make a Heading
<hide> this message

**Comment by wdjacca** [comment]
#will this work?
I hope that worked

**Comment by BarbieCessar** [comment]
`<hi>`

**Comment by amayadwillis** [comment]
###Hello
`<tag>`
```xml
<xml>
<greeting>Hello!</greeting>
</xml>
```

**Comment by am0eba-byte** [comment]
#big words
##not so big words
###little big words

'''
<boop>
       <shmoop ahh="shwing"> little newt is cute </shmoop>
</boop>
'''

**Comment by AliceR98** [comment]
*italics*
**Bold**
***Bold Italic***
>quote

**Comment by Kennaab** [comment]
#Penn State Behrend

##Digit 110

```xml
<xml>
     <tag type="Digit">Digit is fun!</tag>
</xml>

**Comment by wdjacca** [comment]
### Is this working lmao

**Comment by alexvanwoert** [comment]
# 2chainz
     ## 1 chain
```xml
<xml>

</xml>
```

**Comment by thompsonjosh24** [comment]
### Markdown
## Is
# Awesome
 '<person who = Josh Thompson>Me</person>

**Comment by Joelpie** [comment]
# This summer
## Prepare to learn
### M a r k d o w n

**Comment by zteyssier** [comment]
<zoom>
<cpu type="mainframe"> Downloading... </cpu>
</zoom>

**Comment by bwm5473** [comment]
#Heading 1
##Any idea where that icon for the markdown tutorial is?
###Is isn't on my screen.

**Comment by trumerfe** [comment]
Idk if this is gonna work
*hi*
**I am**
<h1>**_Ruby_**</h1>

**Comment by bwm5473** [comment]
`<h1>`

**Comment by bwm5473** [comment]
<h1> Heading 1 </h1>

**Comment by bwm5473** [comment]
<h2>I've got the headings figured out.</h2>

**Comment by bwm5473** [comment]
<h3> Was it the Git Shell we were using? </h3>

**Comment by bwm5473** [comment]
>My cat is meowing without end.<

**Comment by bwm5473** [comment]
>My cat will not stop meowing.

**Comment by bwm5473** [comment]
First Header | Second Header
-------------- | ---------------

**Comment by bwm5473** [comment]
This actually | Works
------------- | -------------

**Comment by bwm5473** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> supported
- [x] list syntax required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

**Comment by bwm5473** [comment]
- [x] Check
- [x] Check
- [ ] <del>Uncheck</del>
