### ISSUE TITLE
Welcome new DIGIT 110 collaborators!

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#65]
Log in to your GitHub account and post in response to this to request me to add you to our textEncoding-Hub repo! Please identify yourself and try writing something in GitHub markdown, too. :-)

**Comment by VocaloidOtaku39** [comment]
My username is VocaloidOtaku39. @ebeshero please add me as a collaborator.

**Comment by SonicSpaceFan025** [comment]
My username is SonicSpaceFan025. @ebeshero Please add me as a collaborator!

**Comment by GarrettStroupe** [comment]
My username is GarrettStroupe. @ebeshero , Please add me as a collaborator.
