### ISSUE TITLE
Welcome DIGIT 110 collaborators!

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textEncoding-Hub#66]
**All DIGIT 110 students:** please respond to this post to request me to add you (your GitHub account) to our textEncoding-Hub repo! Identify yourself and try writing something in GitHub markdown, too. :-) 

```xml
<hello world="digit-110">Welcome to the textEncoding-Hub</hello>
```

**Comment by 03lizchavez** [comment]
My username is @03lizchavez. @ebeshero please add me as a collaborator to this DHClass-Hub

**Comment by rcc5418** [comment]
This is Reece Cullen, please add me.

**Comment by creaturepsu** [comment]
this is charlie vazquez digit 110

**Comment by ceq5032** [comment]
My user name is @ceq5032 , @ebeshero please add me as a collaborator.

**Comment by HadleighJae** [comment]
My username is @HadleighJae. @ebeshero add me as a collaborator to this!

**Comment by TylerDollard** [comment]
My username is TylerDollard. @ebeshero  please add me

**Comment by MadisonSciarrillo** [comment]
My username is MadisonSciarrillo. @ebeshero please add me

**Comment by VocaloidOtaku39** [comment]
My username is VocaloidOtaku39. @ebeshero please add me

**Comment by SonicSpaceFan025** [comment]
My username is SonicSpaceFan025. @ebeshero Please add me as a collaborator!

**Comment by VocaloidOtaku39** [comment]
My username is VocaloidOtaku39. @ebeshero please add me

**Comment by gylertaydos** [comment]
Its Tyler Gaydos, username @gylertaydos. Please add me, @ebeshero

**Comment by creaturepsu** [comment]
My username is @creaturepsu @ebeshero please add me

**Comment by GKon26** [comment]
I am George Koncerak. My username is @GKon26. @ebeshero please add me

**Comment by GarrettStroupe** [comment]
My username is GarrettStroupe. @ebeshero , Please add me as a collaborator.

**Comment by MystKitteh** [comment]
`<add="collaboratorPlease">This is Mistie McColm! My username is @MystKitteh, please add me when you have time!</add>`

**Comment by nhammer514** [comment]
My username is @nhammer514 . @ebeshero Please add me as a collaborator!

**Comment by J-Banko** [comment]
Its Justin Banko. My username is @J-Banko . @ebeshero please add me as a collaborator.

**Comment by hsosia1** [comment]
> My username is @03lizchavez. @ebeshero please add me as a collaborator to this DHClass-Hub



> **All DIGIT 110 students:** please respond to this post to request me to add you (your GitHub account) to our textEncoding-Hub repo! Identify yourself and try writing something in GitHub markdown, too. :-)
> 
> ```
> <hello world="digit-110">Welcome to the textEncoding-Hub</hello>
> ```

My username is hsosia1 @ebeshero  Please add me as a collaborator

**Comment by lgmccurdy** [comment]
Lauren McCurdy, username @lgmccurdy, @ebeshero please add me as a collaborator.

**Comment by sammoniot** [comment]
It's Sam! My username is @sammoniot. @ebeshero please add me as a collaborator.

**Comment by mew-II** [comment]
It's Matthew, My username is @mew-II. @ebeshero please add me as a collaborator.

**Comment by jvs7215** [comment]
<section class = "Digit110">This is Jessica Salemme @jvs7215 </section>
Please add me as a collaborator to the textEncoding-Hub repo! @ebeshero
