### ISSUE TITLE
Can't find "Sandbox" folder under textEncoding directory

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/textEncoding-Hub#7]
Hi! the Sandbox folder does not appear under the textEncoding list (ls) with all the other files when I am in my Git terminal thingie - help? I think I'm typing everything in correctly. Side note: I am using a Mac OS X El Captain.

**Comment by am0eba-byte** [comment]
AH nevermind, I got it! I had to git pull it. Sometimes I have to ask the stupid questions first before I figure it out on my own, haha.

**Comment by ebeshero** [comment]
@am0eba-byte Yay! Part of writing up an issue is sometimes figuring out the problem while writing it up :-)
