### ISSUE TITLE
Comparing XML Projects

### ISSUE THREAD

**Issue by josiahr21** [newtfire/textEncoding-Hub#73]
On the Radical Scatters website, in the Amherst College Library, there was a passage named a156. There were two lines that ran through the text and were coded as:

<rdg corresp="a156.would" xml:id="a156.could">could</rdg>
<rdg corresp="a156.could" xml:id="a156.would">
<add place="infralinear" type="variant">would</add>
</rdg>

This made it easy to understand that there is a line in the text that start at could and would. The markup itself was easy to find as towards the end of the page there was another markup signaling the end of the line using a156.would and a156.could.

On the Emily Dickinson Archive it was pretty hard to find the transcripts. I went through a lot of links trying to find a transcript. I finally found it in the New York Public Library collection. The transcription is a little unorthodox but this is the first page:

Division
1 the |
1 Waters |
2 they |
2 still |
3 cannot |
Division
1 the |
1 Waters |
2 are |
4 vacillating |
5 this |
Emendation
after 1, 2, 3, 4] extra line spacing
Division
1 the |
1 Waters |
2 are |
3 cannot | doubt, ||

I's not very easy to read and isn't even in XML.  There weren't many markups due to it being a standard poem with lines and no images. This markup is not as good as the previous one as there is not as much information that they are providing.

**Comment by ebeshero** [comment]
@josiahr21 I think what you're seeing is the web view, so you're not looking at the angle-bracket markup tags `<element>` that you'd see in the XML under the hood. Projects *do* share this, but not all of them will make it easy to find. 

The XML makes a structure that contributes to the view you see on the website, and also stores information that you can't directly see. So around each of these lines you show, there may be something marking the numbers as line numbers, maybe.
