### ISSUE TITLE
Poem 5 (J 280: 1861/1896)

### ISSUE THREAD

**Issue by 03lizchavez** [newtfire/textEncoding-Hub#75]
Honestly, I forgot to look through the sites through Chrome because I couldn't see the actual XML file the moment I tried to open it. But now that I switched to Chrome, I was just wondering that as they stuck to "Fascicle 16", they show with the images attached each line included. Maybe I'm not understanding it but they altered the lines and added on or switch it around a bit. The handwriting was a bit hard for me to understand but still able to tell it's not word for word. Here the coding shows 
<app>
<rdg wit="#df16 #fh" type="var0">And Finished knowing—then—</rdg>
<rdg wit="#df16" type="var1">And Got through—knowing—then—</rdg>
<rdg wit="#ce #poems3"/>
</app>
when in the image it shows "and Finished know then Crash Got-through"

**Comment by ebeshero** [comment]
@03lizchavez Yes, you're understanding how the revisions were made--only with Emily Dickinson, she didn't cancel out things--she kept alternate options open! It's a little like choosing which line you'd most like to complete the work on a given day based on maybe mood or impression of the world or who you're sharing it with... Does it make the poem a little more like a game I wonder?
