### ISSUE TITLE
Trouble with moving a file into Sandbox

### ISSUE THREAD

**Issue by Beeplosion** [newtfire/textEncoding-Hub#8]
I have been having trouble all day trying to move an image to the sandbox, so far I get to the end but it has trouble constantly trying to direct it to the sandbox

**Comment by ebeshero** [comment]
@Beeplosion I'm about to help another student with a similar problem over Zoom. Want to join us right now in my office Zoom here? 
https://psu.zoom.us/my/ebeshero

**Comment by ebeshero** [comment]
@Beeplosion Okay, let's see if I can walk you through this. Are you online now? Are you trying to use `mv` or `cp` to move the file? If you're stuck on that part, can you show me the commands your entering? 
Are you at the position of the textEncoding-Hub on your local computer when you're tying to copy the file in? 
Where is the source file located?

**Comment by ebeshero** [comment]
@Beeplosion Here's a shortcut: It is perfectly okay to drag and drop a file into the textEncoding-Hub/Sandbox using your file manager or Finder. There's no harm in that. Then go and open your Bash or Terminal to do that sequence:
`git add .`
`git commit -m "your commit message here"`
`git push`

At some point in there, either when you commit or push, you'll probably be prompted to enter your GitHub username and password, so do that carefully!

**Comment by Beeplosion** [comment]
the tricky part is I seem to have done this but when I try to push the image in this pops up:
" git push
fatal: The current branch master has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin master


sorti@DESKTOP-O8NKM44 MINGW64 ~/Documents/GitHub/textEncoding-Hub/Sandbox (master)
$ git push --set-upstream origin master
fatal: 'C:/Users/sorti/Documents/Lillie.jpg' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists."

**Comment by Beeplosion** [comment]
"$ git remote -v
origin  C:/Users/sorti/Documents/Lillie.jpg (fetch)
origin  C:/Users/sorti/Documents/Lillie.jpg (push)
"

**Comment by Beeplosion** [comment]
I somehow made another sandbox within the sandbox

**Comment by ebeshero** [comment]
@Beeplosion Hmmm. This looks to me like you're trying to enter your `git push` from the wrong location! 
You want to navigate to the textEncoding-Hub on your computer to do the `git` commands from there. It looks like your just up in your Documents directory!

So, here's what should happen. If you are trying to push Lillie.jpg to the Sandbox on the remote web repo that we share, you first need to save it to the Sandbox directory of textEncodingHub.
Its file location should be inside textEncoding-Hub/Sandbox
It looks to me like you're trying to push it from your Documents directory. Instead it should be here:
C:/Users/sorti/Documents/GitHub/textEncoding-Hub/Sandbox/Lillie.jpg

**Comment by ebeshero** [comment]
@Beeplosion Hmm. How did you get a Sandbox inside the Sandbox? We will probably need to undo that.

**Comment by ebeshero** [comment]
@Beeplosion Would it help to share your screen over a Zoom session right now? I think I can help you troubleshoot this.
